/* IGeek Typecraft @version 0.x
@link    https://github.com/KabukiStarship/IGeekTypecraft.git
@file    /Item.h
@author  Cale McCollough <https://cookingwithcale.org>
@license Copyright 2015-20 (C) Kabuki Starship <https://kabukistarship.com>.
This Source Code Form is subject to the terms of the Mozilla Public License, 
v. 2.0. If a copy of the MPL was not distributed with this file, you can obtain 
one at <https://mozilla.org/MPL/2.0/>. */
#pragma once
#include <_Config.h>
#ifndef TYPECRAFT_ITEM_DECL
#define TYPECRAFT_ITEM_DECL
namespace Typecraft {
enum {
  cTypecraftNumBlocks = 452,
};

class Item {
 public:
  typedef enum Type {
    Air = 0,
    Stone,
    Grass,
    Dirt,
    Cobblestone,
    OakWoodPlank,
    OakSapling,
    Bedrock,
    FlowingWater,
    StillWater,
    FlowingLava,
    StillLava,
    Sand,
    Gravel,
    GoldOre,
    IronOre,
    CoalOre,
    OakWood,
    OakLeaves,
    Sponge,
    Glass,
    LapisLazuliOre,
    LapisLazuliBlock,
    Dispenser,
    Sandstone,
    NoteBlock,
    Bed,
    PoweredRail,
    DetectorRail,
    StickyPiston,
    Cobweb,
    DeadShrub,
    DeadBush,
    Piston,
    PistonHead,
    Wool,
    Flower,
    Mushroom,
    GoldBlock,
    IronBlock,
    Slab,
    Bricks,
    TNT,
    Bookshelf,
    MossStone,
    Obsidian,
    Torch,
    Fire,
    MonsterSpawner,
    OakWoodStairs,
    Chest,
    RedstoneWire,
    DiamondOre,
    DiamondBlock,
    CraftingTable,
    WheatCrops,
    Farmland,
    Furnace,
    BurningFurnace,
    StandingSignBlock,
    OakDoorBlock,
    Ladder,
    Rail,
    CobblestoneStairs,
    WallMountedSignBlock,
    Lever,
    StonePressurePlate,
    IronDoorBlock,
    WoodenPressurePlate,
    RedstoneOre,
    GlowingRedstoneOre,
    RedstoneTorchOff,
    RedstoneTorchOn,
    StoneButton,
    Snow,
    Ice,
    SnowBlock,
    Cactus,
    Clay,
    SugarCanes,
    Jukebox,
    OakFence,
    Pumpkin,
    Netherrack,
    SoulSand,
    Glowstone,
    NetherPortal,
    JackoLantern,
    CakeBlock,
    RedstoneRepeaterBlockOff,
    RedstoneRepeaterBlockOn,
    Glass,
    BlackStainedGlass,
    WoodenTrapdoor,
    Egg,
    Bricks,
    BrownMushroomBlock,
    RedMushroomBlock,
    IronBars,
    GlassPane,
    MelonBlock,
    PumpkinStem,
    MelonStem,
    Vines,
    OakFenceGate,
    BrickStairs,
    StoneBrickStairs,
    Mycelium,
    LilyPad,
    NetherBrick,
    NetherBrickFence,
    NetherBrickStairs,
    NetherWart,
    EnchantmentTable,
    BrewingStand,
    Cauldron,
    EndPortal,
    EndPortalFrame,
    EndStone,
    DragonEgg,
    RedstoneLampInactive,
    RedstoneLampActive,
    Slab,
    Cocoa,
    SandstoneStairs,
    EmeraldOre,
    EnderChest,
    TripwireHook,
    Tripwire,
    EmeraldBlock,
    SpruceWoodStairs,
    BirchWoodStairs,
    JungleWoodStairs,
    CommandBlock,
    Beacon,
    CobblestoneWall,
    MossyCobblestoneWall,
    FlowerPot,
    Carrots,
    Potatoes,
    WoodenButton,
    MobHead,
    Anvil,
    TrappedChest,
    WeightedPressurePlateLight,
    WeightedPressurePlateHeavy,
    RedstoneComparatorInactive,
    RedstoneComparatorActive,
    DaylightSensor,
    RedstoneBlock,
    NetherQuartzOre,
    Hopper,
    Quartz,
    QuartzStairs,
    ActivatorRail,
    Dropper,
    Clay,
    GlassPane,
    Leaves,
    AcaciaWood,
    AcaciaWoodStairs,
    DarkOakWoodStairs,
    SlimeBlock,
    Barrier,
    IronTrapdoor,
    Prismarine,
    SeaLantern,
    HayBale,
    Carpet,
    HardenedClay,
    BlockofCoal,
    PackedIce,
    Sunflower,
    Lilac,
    FreeStandingBanner,
    WallMountedBanner,
    InvertedDaylightSensor,
    RedSandstone,
    RedSandstoneStairs,
    DoubleRedSandstoneSlab,
    RedSandstoneSlab,
    SpruceFenceGate,
    BirchFenceGate,
    JungleFenceGate,
    DarkOakFenceGate,
    AcaciaFenceGate,
    SpruceFence,
    BirchFence,
    JungleFence,
    DarkOakFence,
    AcaciaFence,
    SpruceDoorBlock,
    BirchDoorBlock,
    JungleDoorBlock,
    AcaciaDoorBlock,
    DarkOakDoorBlock,
    EndRod,
    ChorusPlant,
    ChorusFlower,
    PurpurBlock,
    PurpurPillar,
    PurpurStairs,
    PurpurDoubleSlab,
    PurpurSlab,
    EndStoneBricks,
    BeetrootBlock,
    GrassPath,
    EndGateway,
    RepeatingCommandBlock,
    ChainCommandBlock,
    FrostedIce,
    MagmaBlock,
    NetherWartBlock,
    RedNetherBrick,
    BoneBlock,
    StructureVoid,
    Observer,
    WhiteShulkerBox,
    OrangeShulkerBox,
    MagentaShulkerBox,
    LightBlueShulkerBox,
    YellowShulkerBox,
    LimeShulkerBox,
    PinkShulkerBox,
    GrayShulkerBox,
    LightGrayShulkerBox,
    CyanShulkerBox,
    PurpleShulkerBox,
    BlueShulkerBox,
    BrownShulkerBox,
    GreenShulkerBox,
    RedShulkerBox,
    BlackShulkerBox,
    WhiteGlazedTerracotta,
    OrangeGlazedTerracotta,
    MagentaGlazedTerracotta,
    LightBlueGlazedTerracotta,
    YellowGlazedTerracotta,
    LimeGlazedTerracotta,
    PinkGlazedTerracotta,
    GrayGlazedTerracotta,
    LightGrayGlazedTerracotta,
    CyanGlazedTerracotta,
    PurpleGlazedTerracotta,
    BlueGlazedTerracotta,
    BrownGlazedTerracotta,
    GreenGlazedTerracotta,
    RedGlazedTerracotta,
    BlackGlazedTerracotta,
    Concrete,
    ConcretePowder,
    StructureBlock,
    IronShovel,
    IronPickaxe,
    IronAxe,
    FlintandSteel,
    Apple,
    Bow,
    Arrow,
    Coal,
    Diamond,
    IronIngot,
    GoldIngot,
    IronSword,
    WoodenSword,
    WoodenShovel,
    WoodenPickaxe,
    WoodenAxe,
    StoneSword,
    StoneShovel,
    StonePickaxe,
    StoneAxe,
    DiamondSword,
    DiamondShovel,
    DiamondPickaxe,
    DiamondAxe,
    Stick,
    Bowl,
    MushroomStew,
    GoldenSword,
    GoldenShovel,
    GoldenPickaxe,
    GoldenAxe,
    String,
    Feather,
    Gunpowder,
    WoodenHoe,
    StoneHoe,
    IronHoe,
    DiamondHoe,
    GoldenHoe,
    WheatSeeds,
    Wheat,
    Bread,
    LeatherHelmet,
    LeatherTunic,
    LeatherPants,
    LeatherBoots,
    ChainmailHelmet,
    ChainmailChestplate,
    ChainmailLeggings,
    ChainmailBoots,
    IronHelmet,
    IronChestplate,
    IronLeggings,
    IronBoots,
    DiamondHelmet,
    DiamondChestplate,
    DiamondLeggings,
    DiamondBoots,
    GoldenHelmet,
    GoldenChestplate,
    GoldenLeggings,
    GoldenBoots,
    Flint,
    RawPorkchop,
    CookedPorkchop,
    Painting,
    GoldenApple,
    Sign,
    OakDoor,
    Bucket,
    WaterBucket,
    LavaBucket,
    Minecart,
    Saddle,
    IronDoor,
    Redstone,
    Snowball,
    OakBoat,
    Leather,
    MilkBucket,
    Brick,
    Clay,
    SugarCanes,
    Paper,
    Book,
    Slimeball,
    MinecartWithChest,
    MinecartWithFurnace,
    Egg,
    Compass,
    FishingRod,
    Clock,
    GlowstoneDust,
    Fish,
    CookedFish,
    Ink,
    Bone,
    Sugar,
    Cake,
    Bed,
    RedstoneRepeater,
    Cookie,
    Map,
    Shears,
    Melon,
    PumpkinSeeds,
    MelonSeeds,
    RawBeef,
    Steak,
    RawChicken,
    CookedChicken,
    RottenFlesh,
    EnderPearl,
    BlazeRod,
    GhastTear,
    GoldNugget,
    NetherWart,
    Potion,
    GlassBottle,
    SpiderEye,
    FermentedSpiderEye,
    BlazePowder,
    MagmaCream,
    BrewingStand,
    Cauldron,
    EyeOfEnder,
    GlisteringMelon,
    Spawn,
    BottleOEnchanting,
    FireCharge,
    BookandQuill,
    WrittenBook,
    Emerald,
    ItemFrame,
    FlowerPot,
    Carrot,
    Potato,
    BakedPotato,
    PoisonousPotato,
    EmptyMap,
    GoldenCarrot,
    MobHead,
    CarrotonaStick,
    NetherStar,
    PumpkinPie,
    FireworkRocket,
    FireworkStar,
    EnchantedBook,
    RedstoneComparator,
    NetherBrick,
    NetherQuartz,
    MinecartwithTNT,
    MinecartwithHopper,
    PrismarineShard,
    PrismarineCrystals,
    RawRabbit,
    CookedRabbit,
    RabbitStew,
    RabbitsFoot,
    RabbitHide,
    ArmorStand,
    IronHorseArmor,
    GoldenHorseArmor,
    DiamondHorseArmor,
    Lead,
    NameTag,
    MinecartwithCommandBlock,
    RawMutton,
    CookedMutton,
    Banner,
    SpruceDoor,
    BirchDoor,
    JungleDoor,
    AcaciaDoor,
    DarkOakDoor,
    ChorusFruit,
    PoppedChorusFruit,
    Beetroot,
    BeetrootSeeds,
    BeetrootSoup,
    DragonsBreath,
    SplashPotion,
    SpectralArrow,
    TippedArrow,
    LingeringPotion,
    Shield,
    Elytra,
    SpruceBoat,
    BirchBoat,
    JungleBoat,
    AcaciaBoat,
    DarkOakBoat,
    TotemofUndying,
    ShulkerShell,
    IronNugget,
    Disc13,
    CatDisc,
    BlocksDisc,
    ChirpDisc,
    FarDisc,
    MallDisc,
    MellohiDisc,
    StalDisc,
    StradDisc,
    WardDisc,
    Disc11,
    WaitDisc,
    NUM_ITEMS,
  } Types;

  static const CHA* names[];

  /* Default constructs an initialized Item. */
  Item();

  /* Gets the type. */
  ISC GetType();

  /* Gets the Item Variant. */
  ISC GetVariant();

  /* Gets the condition of the Item. */
  ISC GetCondition();

  /* Sets the condition of the Item. */
  ISC SetContition(ISC condition);

  /* Gets the Item's Label */
  const CHA* Label();

  /* Attempts to set the label POINTER to the new one.
  @return Returns the */
  const CHA* SetLabel(const CHA* label);

  /* Attempts to set the label to a clone of the new one.
  @return Returns null upon success and a pointer to an error string upon
  failure. */
  const CHA* CloneLabel(const CHA* label);

  /* Prints the Item to the console. */
  void Print();

 private:
  const CHA *label_,   //< Proper English Item's label.
      *name_;          //< Name of the Item.
  ISC type_,           //< The type of Item.
      variant_,        //< Variant type of Item.
      condition_,      //< Condition of the Item.
      hunger_,         //< Hunger points you get from this.
      energy_,         //< The points this item has before it expires.
      regen_;          //< Number of points this Item will gain back each frame.
};

/* Gets an Item name. */
Item* Items(ISC item_number);

}  // namespace Typecraft
#endif
